### ISSUE TITLE
Torch memory leak

### ISSUE THREAD

**Issue by pkese** [DiffSharp/DiffSharp#126]
It looks like there is a memory leak with Torch.

I tried to run `tests/Test` with different configurations and my findings are:

#### 1) `backend=Reference`

Appears to run fine. It is slow but runs with constant memory consumption.

#### 2) `backend=Torch, device=CPU`

Runs faster but starts swapping after a while and gets killed by the OOM killer after exhausting all memory and swap space:
```
net params: 1199882
Torch
Duration   |Iters| Ep|  Minib| Loss
0.00:00:04 |   1 | 1 | 1/937 | 2.336721e+000 🡾 New min
0.00:00:08 |   2 | 1 | 2/937 | 2.202248e+000 🡾 New min
0.00:00:11 |   3 | 1 | 3/937 | 1.961257e+000 🡾 New min
0.00:00:22 |   4 | 1 | 4/937 | 1.806348e+000 🡾 New min
0.00:01:41 |   5 | 1 | 5/937 | 1.367965e+000 🡾 New min
<killed>
```

#### 3) `backend=Torch, device=GPU`

Also exhausts memory - this time on GPU:
```
net params: 1199882
Torch
Duration   |Iters| Ep|  Minib| Loss
0.00:00:02 |   1 | 1 | 1/937 | 2.316844e+000 🡾 New min
Unhandled exception. System.Runtime.InteropServices.ExternalException (0x80004005): CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 5.93 GiB total capacity; 4.85 GiB already allocated; 6.06 MiB free; 5.04 GiB reserved in total by PyTorch) (malloc at /pytorch/c10/cuda/CUDACachingAllocator.cpp:289)
```

**Comment by dsyme** [comment]
Thanks!  The report is really useful (and somewhat expected for first analysis....)

**Comment by gbaydin** [comment]
Just a note that the test project under `tests/Test` has been in the repo as a scratch space for quick experiments. There is no expectation that the code in that project is going to do anything useful or relevant in any given commit. I will remove that soon to prevent any misunderstandings like this in the future.

We will have some `examples` folder that will hold working examples that we do expect to always work as expected.

About the memory use issue: I am currently investigating that and we discussed it with @dsyme briefly https://github.com/DiffSharp/DiffSharp/pull/106#issuecomment-636872442 I would like to start by checking if it's a linux-specific issue (about how dotnet runtime memory allocations work in linux as discussed in some of the issues linked from the libtorch2 PR I shared). I currently think that it's not a torch-specific issue. We need to investigate more.

**Comment by dsyme** [comment]
> Just a note that the test project under tests/Test has been in the repo as a scratch space for quick experiments. There is no expectation that the code in that project is going to do anything useful or relevant in any given commit. I will remove that soon to prevent any misunderstandings like this in the future.

Suggest you just rename `tests\Test` to `playground\TestApplication` or the like.  It's useful to have this in the tree but a simple renaming will clarify

**Comment by dsyme** [comment]
@gbaydin FWIW for tests\Test on WIndows at the moment I see

* A quick rise to ~17GB after about 5 iterations, then 25GB after 8
* About 10 iterations completed then I hit Ctrl-C

Just in case it's helpful.  

I'll start a separate thread about how we should test memory usage

**Comment by dsyme** [comment]
@pkese This should be fixed by #133 - there was essentially no collection of unmanaged Torch resources before this, so memory was leaking like crazy :-)

**Comment by dsyme** [comment]
I'll close as I believe the core issue is fixed.  But there may be lingering issues and we definitely need to automate testing on GPU to catch them as we go

**Comment by pkese** [comment]
@dsyme Yes, the memory consumption is now perfectly stable. Congratulations!!!

**Comment by dsyme** [comment]
Great, thanks for confirming!
